### ISSUE TITLE
Max retries exceeded with url: /chain-runs

### ISSUE THREAD

**Issue by aole** [hwchase17/langchain#2145]
Hi,

I keep getting the below warning every time the chain finishes.

`WARNING:root:Failed to persist run: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /chain-runs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8E0B5D0D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))`

Below is the code:
```
import os

from flask import Flask, request, render_template, jsonify

from langchain import LLMMathChain, OpenAI
from langchain.agents import initialize_agent, Tool
from langchain.chat_models import ChatOpenAI
from langchain.memory import ConversationSummaryBufferMemory

os.environ["LANGCHAIN_HANDLER"] = "langchain"

llm = ChatOpenAI(temperature=0)

memory = ConversationSummaryBufferMemory(
    memory_key="chat_history", llm=llm, max_token_limit=100, return_messages=True)

llm_math_chain = LLMMathChain(llm=OpenAI(temperature=0), verbose=True)
tools = [
    Tool(
        name="Calculator",
        func=llm_math_chain.run,
        description="useful for when you need to answer questions about math"
    ), ]

agent = initialize_agent(
    tools, llm, agent="chat-conversational-react-description", verbose=True, memory=memory)


app = Flask(__name__)


@app.route('/')
def index():
    return render_template('index.html', username='N/A')


@app.route('/assist', methods=['POST'])
def assist():
    message = request.json.get('message', '')

    if message:
        response = query_gpt(message)
        return jsonify({"response": response})

    return jsonify({"error": "No message provided"})


def query_gpt(message):
    response = 'Error!'
    try:
        response = agent.run(input=message)
    finally:
        return response

```

Am I doing something wrong here?

Thanks.

**Comment by mgc8** [comment]
I also encountered this error. It appears to be caused by the `os.environ["LANGCHAIN_HANDLER"] = "langchain"`
line, which is present in several parts of the [documentation](https://python.langchain.com/en/latest/modules/agents/agents/examples/chat_conversation_agent.html) but not explained directly. It appears to be a requirement for using cloud-hosted LangChain installations, which is not the case for this example, or any of the applications I was debugging:
https://python.langchain.com/en/latest/tracing/hosted_installation.html

Removing that line clears up the error, and the code runs as before.

**Comment by qwertynik** [comment]
Yes, removing the line helped. Thanks @mgc8. This applies for local installation as well. When docker isn't running this error is thrown.

**Comment by websmyths** [comment]
> I also encountered this error. It appears to be caused by the `os.environ["LANGCHAIN_HANDLER"] = "langchain"` line, which is present in several parts of the [documentation](https://python.langchain.com/en/latest/modules/agents/agents/examples/chat_conversation_agent.html) but not explained directly. It appears to be a requirement for using cloud-hosted LangChain installations, which is not the case for this example, or any of the applications I was debugging: https://python.langchain.com/en/latest/tracing/hosted_installation.html
> 
> Removing that line clears up the error, and the code runs as before.

Removing the line got rid of the error for me, both locally and on Codespaces.

**Comment by aole** [comment]
Removing os.environ["LANGCHAIN_HANDLER"] = "langchain" works for me as well.

Thanks @mgc8

**Comment by Ryangr0** [comment]
I FINALLY found it. This happens because you're not running [tracing](https://python.langchain.com/en/latest/tracing/local_installation.html).

Yes, you actually need to run this to avoid getting these warnings that look like errors, even though it's only a kind of profiler. Here's a docker-compose.yml snippet on how I fixed this:
```
version: '3.7'

services:
    # all your stuff
    langchain-frontend:
      container_name: langchain-frontend
      image: notlangchain/langchainplus-frontend:latest
      ports:
        - 4173:4173
      environment:
        - BACKEND_URL=http://langchain-backend:8000
        - PUBLIC_BASE_URL=http://localhost:8000
        - PUBLIC_DEV_MODE=true
      depends_on:
        - langchain-backend
  
    langchain-backend:
      container_name: langchain-backend
      image: notlangchain/langchainplus:latest
      environment:
        - PORT=8000
        - LANGCHAIN_ENV=local
      ports:
        - 8000:8000
      depends_on:
        - langchain-db
  
    langchain-db:
      container_name: langchain-db
      image: postgres:14.1
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
      ports:
        - 5432:5432
```
