### ISSUE TITLE
SearxSearchWrapper: ('Searx API returned an error: ', 'Too Many Requests')

### ISSUE THREAD

**Issue by AlexW00** [hwchase17/langchain#2251]
The following code produces the "too many requests" error. Using a different host does not fix it.
```py
name="Execute Query Tool"
description="Useful for executing a query against a search engine. Returns the results of the query."

search = SearxSearchWrapper(searx_host="https://www.gruble.de")

def func (query: Query) -> SearchResult:
    searx_results = search.results(query, num_results=10, engines=['wiki'])
    results_stack = [SearchResult.from_searx_result(result) for result in searx_results]
    return results_stack
```

**Comment by Saik0s** [comment]
If you are hosting locally - make sure that you have `server.limiter` set to `false` and `json` is included in `search.formats`. These parameters can be defined in `searxng/settings.yml`.
```
server:
  limiter: false
general:
  debug: true
search:
  formats:
    - html
    - json
```

**Comment by timothymugayi** [comment]
Seems to work though they are other issues of Wikidata and Wikipedia engines not cooperating and timing out. 

Had to resort to turning them off via the settings.yml config in case if it helps anyone 

```
engines:
  - name: wikidata
    engine: wikidata
    shortcut: wd
    timeout: 3.0
    weight: 2
    tests: *tests_infobox
    enabled: False

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    base_url: 'https://{language}.wikipedia.org/'
    enabled: False 

```
